config/routes.rb
Rails.application.routes.draw do
  
  get 'engineering/new'

  get 'engineering/show'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get '/home',      to: 'static_pages#home'
  get '/help',      to: 'static_pages#help'
  get '/about',     to: 'static_pages#about'
  get '/contact',   to: 'static_pages#contact'
  get '/signup',    to: 'users#new'
  get '/login',     to: 'sessions#new'
  post'/login',     to: 'sessions#create'
  delete'/logout',  to: 'sessions#destroy'
  
  get '/new_project',  to: "projects#new"
  post '/new_project', to: "projects#create"
  
  resources :users
  resources :projects
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    
    validates :name,        presence: true,     length: {maximum: 255},
                        uniqueness: true
    validates :position,    presence: true,     length: {maximum: 255}
    validates :developer,   presence: true,     length: {maximum: 255}
    
end

app/models/user.rb
class User < ApplicationRecord
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
    
    has_secure_password 
    
    before_save { self.email = email.downcase }
    #before_save{email.downcase!}  炸弹方法
    
    validates :name,        presence: true,     length: {maximum: 50}
    validates :email,       presence: true,     length: {maximum: 255},
                                format: {with: VALID_EMAIL_REGEX },
                                uniqueness: {case_sensitive: false}
    validates :company,     presence: true,     length: {maximum: 255}
    validates :telephone,   presence: true,     length: {maximum: 11, minimum: 11}
    validates :password,    presence: true,     length: {minimum: 6},
                                allow_nil: true
   
    #返回指定字符的哈希摘要
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : 
                    BCrypt::Engine.cost 
        BCrypt::Password.create(string, cost: cost) 
    end
   
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  #before_filter :set_locale 
  before_action :set_locale

  def set_locale 
    I18n.locale = params[:locale] || I18n.default_locale 
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :logged_in_user,    only: [:new, :index]
  #before_action :              ,    only: [:index]



  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(project_params)  
    add_user_id @project
    if @project.save
      flash[:success] = "创建成功"
      redirect_to @project
    else
      render 'new'
    end
  end
  
  private

    def project_params
      params.require(:project).permit(:name, :position,
                                   :developer)
    end
    
    def add_user_id(project)
      project.user_id = current_user.id
    end
    
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "请先登陆"
        redirect_to login_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  
=begin
    users part
=end
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      #登入用户，然后重新定向到用户的资料界面
      log_in user
      redirect_back_or user
    else
      flash.now[:danger] = '用户名/密码错误' 
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
  

    
=begin
    project part
=end

  def create_project
    
  end
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in_user,    only: [:index, :edit, :update, :destroy]
  before_action :correct_user,      only: [:edit, :update]
  before_action :admin_user,        only: [:destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end
 
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "注册成功！"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
       flash[:success] = "修改成功"
       redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :company,
                                   :telephone, :email,
                                   :password, :password_confirmation,
                                   )
    end
    
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "请先登陆"
        redirect_to login_url
      end
    end
    
    #确保是正确的用户
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user) 
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def full_title(page_title = '') 
        base_title = "Ruby on Rails Tutorial Sample App" 
        if page_title.empty? 
            base_title 
        else 
            page_title + " | " + base_title 
        end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
    

    
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
=begin
    users part
=end
    
    #登入指定的用户
    def log_in(user)
        session[:user_id] = user.id
    end
    
    # 如果指定用户是当前用户，返回 true
    def current_user?(user)
        user == current_user
    end
    
    #返回当前登陆的用户
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    #如果用户已经登陆，返回true，否则返回false
    def logged_in?
        !current_user.nil?  #不为空
    end
    
    #退出当前用户
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
    
    # 重定向到存储的地址或者默认地址
    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end
    
    # 存储后面需要使用的地址
    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end
    
=begin
    project part
=end
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
    
    def default_avatar(size)
        image_tag("risa.jpg", alt: "avatar", size: size)
    end
    
end

app/views/layouts/_footer.html.erb
<footer class="footer"> 
    <small> 
        牡丹江市城市建设档案馆
    </small> 
    <nav> 
        <ul> 
            <li><%= link_to "关于", about_path %></li> 
            <li><%= link_to "内容", contact_path %></li> 
            <li><%= link_to "新闻", '#' %></li> 
        </ul> 
    </nav> 
</footer> 

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse"> 
    <div class="container"> 
        <%= link_to "DEMO", '#', id: "logo" %> 
           <nav> 
               <ul class="nav navbar-nav navbar-right"> 
                   <li><%= link_to "主页", home_path %></li> 
                   <li><%= link_to "帮助", help_path %></li> 
                   
                   <% if logged_in? %>
                       <li><%= link_to "用户", users_path %></li> 
                       <li class="dropdown"> 
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
                               我的账号 <b class="caret"></b>
                           </a>
                           <ul class="dropdown-menu">
                               <li><%= link_to "资料", current_user %></li> 
                               <li><%= link_to "设置", edit_user_path(current_user) %></li>
                               <li><%= link_to "工程", projects_path %></li>
                               <li class="divider"></li> 
                               <li> 
                                   <%= link_to "注销", logout_path, method: "delete" %> 
                               </li> 
                            </ul>
                        </li>
                   <% else %>
                       <li><%= link_to "登陆", login_path %></li> 
                   <% end %>
               </ul> 
           </nav> 
    </div>
</header>

app/views/layouts/_rails_default.html.erb
      
      
      
    <%= csrf_meta_tags %> 
        <%= stylesheet_link_tag 'application', media: 'all', 
                                'data-turbolinks-track': 'reload' %> 
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 

app/views/layouts/_shim.html.erb
       <!--[if lt IE 9]> 
           <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"> 
           </script> 
       <![endif]--> 

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html>
    <head> 
        <title><%= full_title(yield(:title)) %></title>
        <%= render 'layouts/rails_default' %>
        <%= render 'layouts/shim' %>
   </head> 
   
   <body> 
        <%= render 'layouts/header' %>
        <div class="container"> 
           <% flash.each do |message_type, message| %> 
               <div class="alert alert-<%= message_type %>"><%= message %></div> 
           <% end %> 
           <%= yield %> 
           <%= render 'layouts/footer' %> 
           <%= debug(params) if Rails.env.development? %>
        </div>
   </body> 
</html>




        

       
       
       
          
      
        

app/views/projects/_project.html.erb
       
<li>
    <%= link_to project.name, project %>
    <% if project.user_id == current_user.id %>
        | <%= link_to "删除", "#" %>
    <% end %>
    
    <%= link_to project.user_id == current_user.id, "#" %>
</li>

app/views/projects/index.html.erb
<% provide(:title, 'All projects') %>
<h1>工程列表</h1>
<%= link_to "新建", new_project_path %>

<ul class="projects">
    <%#= render @projects %>
    
    <% @projects.each do |project| %>
        <li>
            <%= link_to project.name, project %>
            
            <% @user = User.find_by(params[:name]) %>

            <% if project.user_id == @user.id %>
            | <%= link_to "删除", "#" %>
            <% end %>
            
        </li>
    <% end %>
</ul>

app/views/projects/new.html.erb
<% provide(:title, 'New project') %>
<h1>工程登记</h1>

<div class='row'>
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@project) do |f| %>
            <% @error_list = @project %>
            <%= render 'shared/error_messages' %>
        
            <%= f.label :name, "工程名称" %>
            <%= f.text_field :name, class: 'form-control' %>
            
            <%= f.label :position, "建筑位置" %>
            <%= f.text_field :position, class: 'form-control' %>
            
            <%= f.label :developer, "建设单位" %>
            <%= f.text_field :developer, class: 'form-control' %>
            
            <%= f.submit "提交", class: "btn btn-primary" %>
        
        <% end %>
    </div>
</div>

app/views/projects/show.html.erb
<div class="row"> 
    <aside class="col-md-4"> 
        <section class="user_info"> 
            <h1>
                工程名称： <%= @project.name %> <br/>
                建筑位置： <%= @project.position %> <br/>
                建设单位： <%= @project.developer %> <br/>

            </h1> 
        </section> 
    </aside> 
</div> 

app/views/shared/_error_messages.html.erb
<% if @error_list.errors.any? %> 
    <div id="error_explanation"> 
        <div class="alert alert-danger"> 
            存在 <%= pluralize(@error_list.errors.count, "个错误") %>. 
        </div> 
        <ul> 
        <% @error_list.errors.full_messages.each do |msg| %> 
            <li><%= msg %></li> 
        <% end %> 
        </ul> 
    </div> 
<% end %> 

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>

<h1>About</h1> 
<p> 
    The <a href="http://www.railstutorial.org/"><em>Ruby on Rails 
    Tutorial</em></a> is a 
    <a href="http://www.railstutorial.org/book">book</a> and 
    <a href="http://screencasts.railstutorial.org/">screencast series</a> 
    to teach web development with 
    <a href="http://rubyonrails.org/">Ruby on Rails</a>. 

</p> 

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
    Contact the Ruby on Rails Tutorial about the sample app at the
<a href="http://www.railstutorial.org/contact">contact page</a>. 
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html> 

<h1>Help</h1> 
<p> 
    Get help on the Ruby on Rails Tutorial at the 
    <a href="http://www.railstutorial.org/help">Rails Tutorial help 
    page</a>. 
    To get help on this sample app, see the 
    <a href="http://www.railstutorial.org/book"><em>Ruby on Rails 
    Tutorial</em> book</a>. 
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
    
    <h1>欢迎来到牡丹江市城市建设档案馆</h1>

    <h2> 
        注册账号，进行报建登记。
    </h2>

    <%= link_to "立即注册！", signup_path, class: "btn btn-lg btn-primary" %> 
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"), 
'http://rubyonrails.org/' %>

app/views/users/_user.html.erb
<li>
    <%= default_avatar 100 %>
    <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user?(user) %>
        | <%= link_to "delete", user, method: :delete,
                            data: { confirm: "You sure?" } %>
    <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>修改账户信息</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <% @error_list = @user %>
            <%= render 'shared/error_messages' %>
            
            <%= f.label :name, "姓名" %>
            <%= f.text_field :name, class: 'form-control' %>
            
            <%= f.label :company, "公司" %>
            <%= f.text_field :company, class: 'form-control' %>
            
            <%= f.label :telephone, "手机" %>
            <%= f.text_field :telephone, class: 'form-control' %>
            
            <%= f.label :email, "邮箱" %>
            <%= f.email_field :email, class: 'form-control' %>
            
            <%= f.label :password, "密码" %>
            <%= f.password_field :password, class: 'form-control' %>
            
            <%= f.label :password_confirmation, "确认密码" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            
            <%= f.submit "确认修改", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>用户列表</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>注册账号</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <% @error_list = @user %>
            <%= render 'shared/error_messages' %>
            
            <%= f.label :name, "姓名" %>
            <%= f.text_field :name, class: 'form-control' %>
            
            <%= f.label :company, "公司" %>
            <%= f.text_field :company, class: 'form-control' %>
            
            <%= f.label :telephone, "手机" %>
            <%= f.text_field :telephone, class: 'form-control' %>
            
            <%= f.label :email, "邮箱" %>
            <%= f.email_field :email, class: 'form-control' %>
            
            <%= f.label :password, "密码" %>
            <%= f.password_field :password, class: 'form-control' %>
            
            <%= f.label :password_confirmation, "确认密码" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            
            <%= f.submit "完成注册", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row"> 
    <aside class="col-md-4"> 
        <section class="user_info"> 
            <h1>
                <%= default_avatar 200 %>
                <%= @user.name %> 
            </h1> 
        </section> 
    </aside> 
</div> 